CREATE TABLE IF NOT EXISTS users
(
    id    bigint generated by default as identity not null,
    name  varchar(255) not null,
    email varchar(255) not null,
        constraint pk_user primary key (id),
        constraint uq_user_email unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id    bigint generated by default as identity not null,
    name  varchar(255),
    description  varchar(255),
    is_available boolean,
    owner_id bigint not null,
        constraint pk_item primary key (id),
        constraint fk_item_on_owner foreign key (owner_id) references users (id)
);